--creating tables
CREATE TABLE PHU_locations (
	PHU_ID INT NOT NULL,
	PHU_Name VARCHAR NULL,
	PHU_Lat FLOAT NOT NULL,
	PHU_Long FLOAT NOT NULL,
	PRIMARY KEY (PHU_ID),
	UNIQUE (PHU_Name)
);
CREATE TABLE Case_Status (
	PHU_ID INT NOT NULL,
	Status VARCHAR(20) NULL,
	Outbreak_Related VARCHAR(5) NOT NULL,
	Case_Month INT NOT NULL,
	Case_Year INT NOT NULL,
	FOREIGN KEY (PHU_ID) REFERENCES PHU_locations (PHU_ID)
);
CREATE TABLE Demographics (
	PHU_ID INT NOT NULL,
	Age_Group VARCHAR(5) NOT NULL,
	Gender VARCHAR(15) NULL,
	Status VARCHAR(20) NULL,
	Case_Month INT NOT NULL,
	Case_Year INT NOT NULL,
	FOREIGN KEY (PHU_ID) REFERENCES PHU_locations (PHU_ID)
);
